/**
 * HPOS UI Presets — 5 substantially different visual identities.
 *
 * Each preset defines:
 *  - id, name, description, character
 *  - tokens: light/dark overrides (on top of base LIGHT_TOKENS / DARK_TOKENS)
 *  - prefs: concrete ThemeContext prefs that drive layout, radius, density, typography, sidebar etc.
 *  - effects: extra CSS variables for background treatment, glass, glow, motion
 *
 * Presets are applied centrally by ThemeContext — never duplicated per-screen.
 */

export const PRESET_IDS = ['minimal', 'aurora', 'darkPro', 'soft', 'enterprise']

export const PRESETS = {
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    label: 'Modern Minimal',
    desc: 'Clean & spacious with subtle borders',
    character: 'Clean, airy, editorial. Lots of whitespace, hairline borders, restrained shadows.',
    accent: 'blue',
    motion: { duration: 160, easing: 'cubic-bezier(.2,.8,.3,1)', scale: 1 },
    tokens: {
      light: {
        '--bg': '#ffffff',
        '--surface': '#ffffff',
        '--surface-2': '#f7f7f5',
        '--elevated': '#ffffff',
        '--rail': '#f7f7f5',
        '--rail-fg': '#6f6e69',
        '--rail-fg-on': '#37352f',
        '--rail-hover': 'rgba(55,53,47,.06)',
        '--rail-line': '#e7e7e4',
        '--text': '#37352f',
        '--text-2': '#6f6e69',
        '--muted': '#9a9a96',
        '--line': '#e9e9e8',
        '--hover': 'rgba(55,53,47,.04)',
        '--selected': 'rgba(55,53,47,.08)',
        '--shadow': '0 1px 2px rgba(55,53,47,.06), 0 8px 24px -16px rgba(55,53,47,.10)',
      },
      dark: {
        '--bg': '#191919',
        '--surface': '#202020',
        '--surface-2': '#262626',
        '--elevated': '#2c2c2c',
        '--rail': '#202020',
        '--rail-fg': '#9b9b9b',
        '--rail-fg-on': '#e6e6e4',
        '--rail-hover': 'rgba(255,255,255,.06)',
        '--rail-line': 'rgba(255,255,255,.09)',
        '--text': '#e6e6e4',
        '--text-2': '#b3b3ae',
        '--muted': '#8e8e89',
        '--line': '#2e2e2c',
        '--hover': 'rgba(255,255,255,.05)',
        '--selected': 'rgba(255,255,255,.09)',
        '--shadow': '0 1px 2px rgba(0,0,0,.35), 0 8px 24px -12px rgba(0,0,0,.45)',
      },
    },
    prefs: {
      radius: 10,
      density: 'Comfortable',
      railRadius: 8,
      railItemH: 38,
      railGap: 3,
      railWidth: 194,
      railPad: 10,
      railSharp: 14,
      railInset: 0,
      barH: 56,
      barPadX: 20,
      barGap: 9,
      barTitle: 15,
      barTitleWeight: 700,
      barRadius: 14,
      cmpRadius: 6,
      cmpHeight: 32,
      cmpPadX: 14,
      cmpFont: 12.5,
      cmpWeight: 600,
      cmpBorder: 1,
      cmpGap: 7,
      cmpShadow: false,
      fontId: 'system',
      fontWeight: 500,
      headingWeight: 700,
      fontTracking: 0,
      headingTracking: -20,
      lineHeight: 150,
    },
    effects: {
      bgStyle: 'solid',
      cardStyle: 'bordered',
      sidebarStyle: 'flat',
      borderStyle: 'subtle',
      shadowStyle: 'minimal',
      blur: 0,
    },
  },

  aurora: {
    id: 'aurora',
    name: 'Aurora',
    label: 'Glass / Aurora',
    desc: 'Glass surfaces with soft gradients & blur',
    character: 'Translucent, luminous, ethereal. Gradient washes, backdrop blur, soft glow.',
    accent: 'violet',
    motion: { duration: 220, easing: 'cubic-bezier(.16,1,.3,1)', scale: 1 },
    tokens: {
      light: {
        '--bg': '#f8fafc',
        '--surface': 'rgba(255,255,255,0.82)',
        /* Near-opaque surface for floating layers (dropdowns, pickers,
           modals, toasts): they sit over live text, so 0.82 alpha made the
           page behind readable through them — doubled, unreadable text. */
        '--surface-float': 'rgba(255,255,255,0.96)',
        '--surface-2': 'rgba(241,245,249,0.9)',
        '--elevated': 'rgba(255,255,255,0.92)',
        '--rail': 'rgba(248,250,252,0.75)',
        '--rail-fg': '#64748b',
        '--rail-fg-on': '#0f172a',
        '--rail-hover': 'rgba(99,102,241,.08)',
        '--rail-line': 'rgba(226,232,240,0.7)',
        '--text': '#1e293b',
        '--text-2': '#64748b',
        '--muted': '#94a3b8',
        '--line': 'rgba(226,232,240,0.85)',
        '--hover': 'rgba(99,102,241,.04)',
        '--selected': 'rgba(99,102,241,.08)',
        '--shadow': '0 4px 24px -8px rgba(99,102,241,.12), 0 1px 3px rgba(0,0,0,.04)',
        '--success': '#10b981',
        '--warning': '#f59e0b',
        '--danger': '#ef4444',
      },
      dark: {
        '--bg': '#0f172a',
        '--surface': 'rgba(30,41,59,0.78)',
        '--surface-float': 'rgba(30,41,59,0.94)',
        '--surface-2': 'rgba(51,65,85,0.5)',
        '--elevated': 'rgba(51,65,85,0.85)',
        '--rail': 'rgba(15,23,42,0.75)',
        '--rail-fg': '#94a3b8',
        '--rail-fg-on': '#f1f5f9',
        '--rail-hover': 'rgba(139,92,246,.12)',
        '--rail-line': 'rgba(51,65,85,0.5)',
        '--text': '#f1f5f9',
        '--text-2': '#94a3b8',
        '--muted': '#64748b',
        '--line': 'rgba(51,65,85,0.6)',
        '--hover': 'rgba(139,92,246,.08)',
        '--selected': 'rgba(139,92,246,.14)',
        '--shadow': '0 8px 32px -12px rgba(0,0,0,.6), 0 1px 3px rgba(0,0,0,.3), 0 0 0 1px rgba(139,92,246,.08)',
        '--success': '#34d399',
        '--warning': '#fbbf24',
        '--danger': '#f87171',
      },
    },
    prefs: {
      radius: 18,
      density: 'Comfortable',
      railRadius: 12,
      railItemH: 40,
      railGap: 4,
      railWidth: 204,
      railPad: 12,
      railSharp: 14,
      railInset: 8,
      barH: 60,
      barPadX: 22,
      barGap: 10,
      barTitle: 16,
      barTitleWeight: 700,
      barRadius: 14,
      cmpRadius: 12,
      cmpHeight: 36,
      cmpPadX: 18,
      cmpFont: 13,
      cmpWeight: 600,
      cmpBorder: 1,
      cmpGap: 8,
      cmpShadow: true,
      fontId: 'inter',
      fontWeight: 500,
      headingWeight: 700,
      fontTracking: 0,
      headingTracking: -25,
      lineHeight: 155,
    },
    effects: {
      bgStyle: 'aurora',
      cardStyle: 'glass',
      sidebarStyle: 'glass',
      borderStyle: 'soft',
      shadowStyle: 'glow',
      blur: 16,
    },
  },

  darkPro: {
    id: 'darkPro',
    name: 'Dark Pro',
    label: 'Dark Pro',
    desc: 'Premium dark with high contrast & precision',
    character: 'Premium, focused, high-contrast. Deep blacks, refined borders, accent lighting.',
    accent: 'blue',
    motion: { duration: 140, easing: 'cubic-bezier(.4,0,.2,1)', scale: 1 },
    tokens: {
      light: {
        '--bg': '#fcfcfc',
        '--surface': '#ffffff',
        '--surface-2': '#f4f4f5',
        '--elevated': '#ffffff',
        '--rail': '#09090b',
        '--rail-fg': '#a1a1aa',
        '--rail-fg-on': '#ffffff',
        '--rail-hover': 'rgba(255,255,255,.07)',
        '--rail-line': '#1a1a1e',
        '--text': '#18181b',
        '--text-2': '#52525b',
        '--muted': '#71717a',
        '--line': '#e4e4e7',
        '--hover': 'rgba(0,0,0,.03)',
        '--selected': 'rgba(0,0,0,.06)',
        '--shadow': '0 1px 2px rgba(0,0,0,.06), 0 4px 12px -4px rgba(0,0,0,.08)',
      },
      dark: {
        '--bg': '#09090b',
        '--surface': '#18181b',
        '--surface-2': '#232326',
        '--elevated': '#27272a',
        '--rail': '#09090b',
        '--rail-fg': '#71717a',
        '--rail-fg-on': '#fafafa',
        '--rail-hover': 'rgba(255,255,255,.06)',
        '--rail-line': '#232326',
        '--text': '#fafafa',
        '--text-2': '#a1a1aa',
        '--muted': '#71717a',
        '--line': '#27272a',
        '--hover': 'rgba(255,255,255,.04)',
        '--selected': 'rgba(255,255,255,.08)',
        '--shadow': '0 1px 2px rgba(0,0,0,.4), 0 16px 40px -16px rgba(0,0,0,.65)',
      },
    },
    prefs: {
      radius: 10,
      density: 'Comfortable',
      railRadius: 6,
      railItemH: 36,
      railGap: 2,
      railWidth: 200,
      railPad: 10,
      railSharp: 14,
      railInset: 0,
      barH: 52,
      barPadX: 18,
      barGap: 8,
      barTitle: 14,
      barTitleWeight: 800,
      barRadius: 14,
      cmpRadius: 6,
      cmpHeight: 32,
      cmpPadX: 14,
      cmpFont: 12.5,
      cmpWeight: 700,
      cmpBorder: 1,
      cmpGap: 6,
      cmpShadow: false,
      fontId: 'geometric',
      fontWeight: 500,
      headingWeight: 800,
      fontTracking: -10,
      headingTracking: -40,
      lineHeight: 145,
    },
    effects: {
      bgStyle: 'solid',
      cardStyle: 'elevated',
      sidebarStyle: 'contrast',
      borderStyle: 'sharp',
      shadowStyle: 'deep',
      blur: 0,
    },
  },

  soft: {
    id: 'soft',
    name: 'Soft',
    label: 'Soft Modern',
    desc: 'Warm & rounded with friendly energy',
    character: 'Friendly, approachable, warm. Generous radius, soft surfaces, smooth milk.',
    accent: 'rose',
    motion: { duration: 260, easing: 'cubic-bezier(.34,1.26,.64,1)', scale: 1 },
    tokens: {
      light: {
        '--bg': '#fdfcfb',
        '--surface': '#ffffff',
        '--surface-2': '#fef7f0',
        '--elevated': '#ffffff',
        '--rail': '#fff7ed',
        '--rail-fg': '#78716c',
        '--rail-fg-on': '#44403c',
        '--rail-hover': 'rgba(251,113,133,.08)',
        '--rail-line': '#ffedd5',
        '--text': '#292524',
        '--text-2': '#78716c',
        '--muted': '#a8a29e',
        '--line': '#f5f5f4',
        '--hover': 'rgba(251,113,133,.04)',
        '--selected': 'rgba(251,113,133,.08)',
        '--shadow': '0 2px 12px -4px rgba(120,113,108,.10), 0 1px 3px rgba(120,113,108,.05)',
      },
      dark: {
        '--bg': '#1c1917',
        '--surface': '#292524',
        '--surface-2': '#44403c',
        '--elevated': '#44403c',
        '--rail': '#292524',
        '--rail-fg': '#a8a29e',
        '--rail-fg-on': '#f5f5f4',
        '--rail-hover': 'rgba(251,113,133,.10)',
        '--rail-line': '#44403c',
        '--text': '#f5f5f4',
        '--text-2': '#a8a29e',
        '--muted': '#78716c',
        '--line': '#44403c',
        '--hover': 'rgba(251,113,133,.06)',
        '--selected': 'rgba(251,113,133,.10)',
        '--shadow': '0 4px 24px -8px rgba(0,0,0,.4), 0 1px 3px rgba(0,0,0,.2)',
      },
    },
    prefs: {
      radius: 20,
      density: 'Comfortable',
      railRadius: 14,
      railItemH: 42,
      railGap: 4,
      railWidth: 206,
      railPad: 12,
      railSharp: 16,
      railInset: 8,
      barH: 58,
      barPadX: 20,
      barGap: 10,
      barTitle: 16,
      barTitleWeight: 700,
      barRadius: 16,
      cmpRadius: 14,
      cmpHeight: 38,
      cmpPadX: 18,
      cmpFont: 13,
      cmpWeight: 600,
      cmpBorder: 1,
      cmpGap: 8,
      cmpShadow: false,
      fontId: 'rounded',
      fontWeight: 500,
      headingWeight: 700,
      fontTracking: 0,
      headingTracking: -15,
      lineHeight: 160,
    },
    effects: {
      bgStyle: 'soft',
      cardStyle: 'soft',
      sidebarStyle: 'soft',
      borderStyle: 'soft',
      shadowStyle: 'soft',
      blur: 0,
    },
  },

  enterprise: {
    id: 'enterprise',
    name: 'Enterprise',
    label: 'Compact / Enterprise',
    desc: 'Dense & precise for power users',
    character: 'Efficient, dense, razor-sharp. Tight spacing, sharp edges, maximum information.',
    accent: 'slate',
    motion: { duration: 110, easing: 'cubic-bezier(.4,0,1,1)', scale: 1 },
    tokens: {
      light: {
        '--bg': '#ffffff',
        '--surface': '#ffffff',
        '--surface-2': '#f8fafc',
        '--elevated': '#ffffff',
        '--rail': '#f1f5f9',
        '--rail-fg': '#475569',
        '--rail-fg-on': '#0f172a',
        '--rail-hover': 'rgba(15,23,42,.05)',
        '--rail-line': '#e2e8f0',
        '--text': '#0f172a',
        '--text-2': '#475569',
        '--muted': '#64748b',
        '--line': '#e2e8f0',
        '--hover': 'rgba(15,23,42,.03)',
        '--selected': 'rgba(15,23,42,.06)',
        '--shadow': '0 1px 2px rgba(15,23,42,.06), 0 1px 3px rgba(15,23,42,.04)',
      },
      dark: {
        '--bg': '#0f172a',
        '--surface': '#1e293b',
        '--surface-2': '#334155',
        '--elevated': '#1e293b',
        '--rail': '#020617',
        '--rail-fg': '#64748b',
        '--rail-fg-on': '#f1f5f9',
        '--rail-hover': 'rgba(255,255,255,.05)',
        '--rail-line': '#1e293b',
        '--text': '#f1f5f9',
        '--text-2': '#94a3b8',
        '--muted': '#64748b',
        '--line': '#334155',
        '--hover': 'rgba(255,255,255,.04)',
        '--selected': 'rgba(255,255,255,.06)',
        '--shadow': '0 1px 2px rgba(0,0,0,.4), 0 4px 12px -6px rgba(0,0,0,.4)',
      },
    },
    prefs: {
      radius: 6,
      density: 'Compact',
      railRadius: 4,
      railItemH: 30,
      railGap: 1,
      railWidth: 186,
      railPad: 6,
      railSharp: 14,
      railInset: 0,
      barH: 44,
      barPadX: 14,
      barGap: 6,
      barTitle: 13,
      barTitleWeight: 700,
      barRadius: 14,
      cmpRadius: 4,
      cmpHeight: 28,
      cmpPadX: 10,
      cmpFont: 11.5,
      cmpWeight: 700,
      cmpBorder: 1,
      cmpGap: 6,
      cmpShadow: false,
      fontId: 'system',
      fontWeight: 500,
      headingWeight: 700,
      fontTracking: 10,
      headingTracking: -10,
      lineHeight: 140,
    },
    effects: {
      bgStyle: 'solid',
      cardStyle: 'sharp',
      sidebarStyle: 'flat',
      borderStyle: 'sharp',
      shadowStyle: 'minimal',
      blur: 0,
    },
  },
}

export function getPreset(id) {
  return PRESETS[id] || PRESETS.minimal
}

export function presetKeys() {
  return Object.keys(PRESETS)
}

/**
 * Returns CSS variables for a preset's palette (per theme).
 */
export function presetTokens(presetId, theme) {
  const p = getPreset(presetId)
  return p.tokens[theme] || p.tokens.light
}

/**
 * Returns prefs that a preset wants to apply. These are merged over the
 * current prefs when the user picks a preset.
 */
export function presetPrefs(presetId) {
  return getPreset(presetId).prefs
}

export function presetMotion(presetId) {
  return getPreset(presetId).motion
}

export function presetEffects(presetId) {
  return getPreset(presetId).effects
}

export const PRESET_ORDER = ['minimal', 'aurora', 'darkPro', 'soft', 'enterprise']
